name: Publish snapshot to Hangar
# Run this on pushes to main and if there's a tag
on:
  push:
    branches:
      - main
      - 'refs/tags/*'

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "gradle"
      # Publish to Hangar using the gradle plugin
      # This outputs: Successfully published VillagerLobotomy version 1.2-snapshot-4f5226c to Hangar: https://hangar.papermc.io/mja00/VillagerLobotomy/versions/1.2-snapshot-4f5226c at the end
      - name: Publish
        id: publish
        env:
          HANGAR_API_KEY: ${{ secrets.HANGAR_API_TOKEN }}
        run: |
          output=$(./gradlew build publishPluginPublicationToHangar --stacktrace)
          echo "$output"
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Parse publish result
        id: parse-publish-result
        run: |
          version=$(echo "${{ steps.publish.outputs.output }}" | grep "Successfully published VillagerLobotomy version" | sed -E 's/.*version ([^ ]+) to.*/\1/')
          url=$(echo "${{ steps.publish.outputs.output }}" | grep "Successfully published VillagerLobotomy version" | sed -E 's/.*Hangar: ([^ ]+).*/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "url=$url" >> $GITHUB_OUTPUT
      - name: Get current date in ISO 8601 format
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Announce to Discord
        uses: tsickert/discord-webhook@v6.0.0
        # Post webhook if this is a tag run
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && (!contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]')) && startsWith(github.ref, 'refs/tags/')
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: Villager Lobotomy
          avatar-url: https://cdn.modrinth.com/data/sQ1MQcd2/16cd6db5088b78b41c29cda8eda940f5390efa08.png
          embed-title: "New VillagerLobotomy update!"
          embed-description: "${{ steps.parse-publish-result.outputs.version }} is now available on Hangar! [Click here to download](${{ steps.parse-publish-result.outputs.url }})"
          embed-thumbnail-url: https://hangarcdn.papermc.io/avatars/project/3678.webp?v=1
          embed-timestamp: "${{ steps.date.outputs.date }}"
